# Site settings
title: The Future of Archaeology
description: "A couple of ideas of where I believe Archaeology is going"
url: "http://www.jacoporabolini.com/emerald"
author:
  name: "Jeffrey Wilson"
  email: "jeffreyhwilson.90@gmail.com"
  url: "https://jwilson90.github.io/Final-Project-Jeffrey-Wilson/"

# Build settings
 # Change this to your relative path (ex: /blog/), or leave just a /
markdown: kramdown
source: .
destination: ./_site
permalink: /:title
paginate: 8
paginate_path: /page:num/

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Plugins
gems:
  - jekyll-paginate

# Custom variables
version: "1.1.0"

# Options
custom_header: false
custom_nav_footer: false
reverse: false
